### PR TITLE
ported Gtk, updated sugargame and some miscellaneous fixes

### PR DESCRIPTION
**Pull request by yell0wfl4sh**
- Ported to Gtk3
- Updated sugargame to v1.2
- Updated license to GPLv3+

@quozl please review!

### CODE REVIEW

**Comment by quozl** [comment]
My preference is to have permission from the author before changing license from GPLv2+ to GPLv3+.

**Comment by yell0wfl4sh** [comment]
activity.info had GPLv3 but the code had GPLv2+, so just tried to remove ambiguity. I'll take care of it in future. Do you want me to revert back?

**Comment by quozl** [comment]
Up to you; either;
* get permission from the author, or;
* do not change license.

**Comment by yell0wfl4sh** [comment]
Reverted back to original license in ```reversi.py``` and updated license in ```activity.info``` to GPLv2+ accordingly.

Merging since already reviewed.

**Comment by quozl** [comment]
Reviewed bd3759d.

**Pull request merged**
