### PR TITLE
port to python 3

### PR DESCRIPTION
**Pull request by ayushnawal**
@quozl please review, tested the game successfully.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Reviewed;

* [ ] not part of Sugar desktop.
* [ ] not available on activities.sugarlabs.org once it is Python 3,

**Comment by ayushnawal** [comment]
I didn't know that, sorry :grimacing: 

done as suggested.

**Comment by quozl** [comment]
Wording we use in other activities in this classification is "is not part of the Sugar desktop, but can be added."

Sorry about that.  I've not had time to detect this recently, so several changes got past me.  I've updated many just now.

Here's a search result to support my assertion;

```sh
for x in $(grep -l "is not part of the Sugar desktop" *activity/README.md); do
  (cd $(dirname $x); git remote -v |grep origin|grep fetch|awk '{print $2;}');
done
```

```log
git@github.com:sugarlabs/activity-abacus.git
git@github.com:sugarlabs/AEIOU.git
git@github.com:sugarlabs/ball-and-brick-activity.git
git@github.com:sugarlabs/block-party-activity
git@github.com:sugarlabs/Bounce
git@github.com:sugarlabs/cardsort.git
git@github.com:sugarlabs/clock-activity.git
git@github.com:sugarlabs/convert.git
git@github.com:sugarlabs/cookie-search-activity.git
git@github.com:godiard/develop-activity.git
git@github.com:sugarlabs/dimensions
git@github.com:sugarlabs/distance-activity.git
git@github.com:sugarlabs/finance-activity.git
git@github.com:sugarlabs/flappy-birds-activity.git
git@github.com:sugarlabs/fractionbounce.git
git@github.com:sugarlabs/gcompris-wrapper-activity.git
git@github.com:sugarlabs/i-can-read-activity.git
git@github.com:sugarlabs/iknowEditor.git
git@github.com:sugarlabs/iknowmyabcs
git@github.com:quozl/implode-activity.git
git@github.com:sugarlabs/infoslicer
git@github.com:sugarlabs/lettermatch.git
git@github.com:sugarlabs/letters.git
git@github.com:sugarlabs/level-activity.git
git@github.com:sugarlabs/locosugar
git@github.com:sugarlabs/memorize-activity.git
git@github.com:sugarlabs/moon-activity.git
git@github.com:sugarlabs/nutrition.git
git@github.com:sugarlabs/playgo-activity.git
git@github.com:sugarlabs/pointillism-activity.git
git@github.com:godiard/poll-activity.git
git@github.com:sugarlabs/portfolio-activity.git
git@github.com:sugarlabs/readetexts.git
git@github.com:sugarlabs/stick-hero-activity.git
git@github.com:sugarlabs/stopwatch.git
git@github.com:sugarlabs/story.git
git@github.com:sugarlabs/textdungeon.git
git@github.com:sugarlabs/activity-turtle-confusion.git
git@github.com:sugarlabs/turtlepond.git
git@github.com:sugarlabs/tuxpaint-wrapper-activity.git
git@github.com:sugarlabs/typing-turtle-activity.git
git@github.com:sugarlabs/VncLauncher
```

**Comment by ayushnawal** [comment]
will keep it in mind.

I have made the same changes in other pr too. please review them :grin:

**Comment by srevinsaju** [comment]
@ayushnawal, tested this port, no warnings or errors, but on chosing a color for player 1, I can change the color of the blocks to a manual color

image

But on choosing white, it still appears yellow (the background color of yellow), maybe its not a fault of your port, but can you help fix it?
image


Also, the activity does not restore its game status on restore from Journal.

**Comment by srevinsaju** [comment]
This issue mentioned here https://github.com/sugarlabs/reversi-activity/pull/5#issuecomment-578260797 has not happened after the port, so this port is ready to be merged. @quozl

**Pull request merged**
